server:
  port: 9002
  
spring:  jpa:    hibernate:      ddl-auto: update
    show-sql: true
#Oracle Settings   
  datasource:    url: jdbc:oracle:thin:@localhost:1522:orcl
    username: system
    password: Vamshi123
    driver-class-name: oracle.jdbc.OracleDriver
  
      
 #Logging      
logging:
  level:
    org.springframework.web: ERROR
    com.example.logging: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    path: F:/samples/logging/api.log
#need to change version in pom.xml <version>2.4.4</version>